#prefix = ""

#Parameters
p = 25000 #Number of data sets drawn from prior predictive
nobservations = 2000
R = 100 #number of reference distributions
upper.bound = 2000 #bin all observations bigger than upper.bound together
nbins = 50
breaks = seq(0, upper.bound, length.out = nbins)

#Set bandwith so as to mimic the histograms
bandwidth = upper.bound/nbins
#extract mids from the histograms
mids = breaks[-1] - (breaks[-1]-breaks[-nbins])/2

#Load data generated by toggle_switch_summary.R
filename = paste0(prefix,"toggle.binned.p",p,".nobs", nobservations, ".RData")
load(filename)

#Binning and svd
binned.data.matrix = t(sapply(binned.data, function(x) x[[1]]))
binned.data.svd = svd(binned.data.matrix)
first.col.A = binned.data.svd$u[,1]

#Choose references as the R percentiles of first column of A
reference.order = order(first.col.A)
reference.index = reference.order[c(1,(1:(R-1))*(p/R),p)]

#matrix with weights for mixtures
prob.mat = binned.data.matrix[reference.index,]/nobservations

#Load full summary stat for all R references
filename2 = paste0(prefix,"summary.full.p",p,".nobs", nobservations, ".RData")
load(filename2)

summary.full.matrix = t(sapply(summary.stat.full, function(x) x))
#replace -Inf with -1000
summary.full.matrix = pmax(summary.full.matrix,-1000)

summary.full.svd = svd(summary.full.matrix)

#Number of principal components
r = 11
M = rbind(diag(1,r),matrix(0,R+1-r,r))
H = summary.full.svd$v%*%M

summary.stat = function(y){
  S = summary_full(y,bandwidth,prob.mat,mids)
  S = pmax(S,-1000)
  S.red = S%*%H
  return(S.red)
}